export type OscarNominee = {
  title: string
  director: string
  isWinner: boolean
  releaseYear: number
}

export const oscarData: Record<number, OscarNominee[]> = {
  1929: [
    { title: "Wings", director: "William A. Wellman", isWinner: true, releaseYear: 1927 },
    { title: "The Racket", director: "Lewis Milestone", isWinner: false, releaseYear: 1928 },
    { title: "Seventh Heaven", director: "Frank Borzage", isWinner: false, releaseYear: 1927 },
  ],
  1930: [
    { title: "The Broadway Melody", director: "Harry Beaumont", isWinner: true, releaseYear: 1929 },
    { title: "Alibi", director: "Roland West", isWinner: false, releaseYear: 1929 },
    { title: "Hollywood Revue of 1929", director: "Charles Reisner", isWinner: false, releaseYear: 1929 },
    { title: "In Old Arizona", director: "Raoul Walsh", isWinner: false, releaseYear: 1929 },
    { title: "The Patriot", director: "Ernst Lubitsch", isWinner: false, releaseYear: 1928 },
  ],
  1931: [
    { title: "All Quiet on the Western Front", director: "Lewis Milestone", isWinner: true, releaseYear: 1930 },
    { title: "The Big House", director: "George Hill", isWinner: false, releaseYear: 1930 },
    { title: "Disraeli", director: "Alfred E. Green", isWinner: false, releaseYear: 1929 },
    { title: "The Divorcee", director: "Robert Z. Leonard", isWinner: false, releaseYear: 1930 },
    { title: "The Love Parade", director: "Ernst Lubitsch", isWinner: false, releaseYear: 1929 },
  ],
  1932: [
    { title: "Cimarron", director: "Wesley Ruggles", isWinner: true, releaseYear: 1931 },
    { title: "East Lynne", director: "Frank Lloyd", isWinner: false, releaseYear: 1931 },
    { title: "The Front Page", director: "Lewis Milestone", isWinner: false, releaseYear: 1931 },
    { title: "Skippy", director: "Norman Taurog", isWinner: false, releaseYear: 1931 },
    { title: "Trader Horn", director: "W.S. Van Dyke", isWinner: false, releaseYear: 1931 },
  ],
  1933: [
    { title: "Grand Hotel", director: "Edmund Goulding", isWinner: true, releaseYear: 1932 },
    { title: "Arrowsmith", director: "John Ford", isWinner: false, releaseYear: 1931 },
    { title: "Bad Girl", director: "Frank Borzage", isWinner: false, releaseYear: 1931 },
    { title: "The Champ", director: "King Vidor", isWinner: false, releaseYear: 1931 },
    { title: "Five Star Final", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1931 },
    { title: "One Hour with You", director: "Ernst Lubitsch", isWinner: false, releaseYear: 1932 },
    { title: "Shanghai Express", director: "Josef von Sternberg", isWinner: false, releaseYear: 1932 },
    { title: "The Smiling Lieutenant", director: "Ernst Lubitsch", isWinner: false, releaseYear: 1931 },
  ],
  1934: [
    { title: "Cavalcade", director: "Frank Lloyd", isWinner: true, releaseYear: 1933 },
    { title: "A Farewell to Arms", director: "Frank Borzage", isWinner: false, releaseYear: 1932 },
    { title: "42nd Street", director: "Lloyd Bacon", isWinner: false, releaseYear: 1933 },
    { title: "I Am a Fugitive from a Chain Gang", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1932 },
    { title: "Lady for a Day", director: "Frank Capra", isWinner: false, releaseYear: 1933 },
    { title: "Little Women", director: "George Cukor", isWinner: false, releaseYear: 1933 },
    { title: "The Private Life of Henry VIII", director: "Alexander Korda", isWinner: false, releaseYear: 1933 },
    { title: "She Done Him Wrong", director: "Lowell Sherman", isWinner: false, releaseYear: 1933 },
    { title: "Smilin' Through", director: "Sidney Franklin", isWinner: false, releaseYear: 1932 },
    { title: "State Fair", director: "Henry King", isWinner: false, releaseYear: 1933 },
  ],
  1935: [
    { title: "It Happened One Night", director: "Frank Capra", isWinner: true, releaseYear: 1934 },
    { title: "The Barretts of Wimpole Street", director: "Sidney Franklin", isWinner: false, releaseYear: 1934 },
    { title: "Cleopatra", director: "Cecil B. DeMille", isWinner: false, releaseYear: 1934 },
    { title: "Flirtation Walk", director: "Frank Borzage", isWinner: false, releaseYear: 1934 },
    { title: "The Gay Divorcee", director: "Mark Sandrich", isWinner: false, releaseYear: 1934 },
    { title: "Here Comes the Navy", director: "Lloyd Bacon", isWinner: false, releaseYear: 1934 },
    { title: "The House of Rothschild", director: "Alfred Werker", isWinner: false, releaseYear: 1934 },
    { title: "Imitation of Life", director: "John M. Stahl", isWinner: false, releaseYear: 1934 },
    { title: "One Night of Love", director: "Victor Schertzinger", isWinner: false, releaseYear: 1934 },
    { title: "The Thin Man", director: "W.S. Van Dyke", isWinner: false, releaseYear: 1934 },
    { title: "Viva Villa!", director: "Jack Conway", isWinner: false, releaseYear: 1934 },
    { title: "The White Parade", director: "Irving Cummings", isWinner: false, releaseYear: 1934 },
  ],
  1936: [
    { title: "Mutiny on the Bounty", director: "Frank Lloyd", isWinner: true, releaseYear: 1935 },
    { title: "Alice Adams", director: "George Stevens", isWinner: false, releaseYear: 1935 },
    { title: "Broadway Melody of 1936", director: "Roy Del Ruth", isWinner: false, releaseYear: 1935 },
    { title: "Captain Blood", director: "Michael Curtiz", isWinner: false, releaseYear: 1935 },
    { title: "David Copperfield", director: "George Cukor", isWinner: false, releaseYear: 1935 },
    { title: "The Informer", director: "John Ford", isWinner: false, releaseYear: 1935 },
    { title: "Les Misérables", director: "Richard Boleslawski", isWinner: false, releaseYear: 1935 },
    { title: "The Lives of a Bengal Lancer", director: "Henry Hathaway", isWinner: false, releaseYear: 1935 },
    { title: "A Midsummer Night's Dream", director: "Max Reinhardt", isWinner: false, releaseYear: 1935 },
    { title: "Naughty Marietta", director: "W.S. Van Dyke", isWinner: false, releaseYear: 1935 },
    { title: "Ruggles of Red Gap", director: "Leo McCarey", isWinner: false, releaseYear: 1935 },
    { title: "Top Hat", director: "Mark Sandrich", isWinner: false, releaseYear: 1935 },
  ],
  1937: [
    { title: "The Great Ziegfeld", director: "Robert Z. Leonard", isWinner: true, releaseYear: 1936 },
    { title: "Anthony Adverse", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1936 },
    { title: "Dodsworth", director: "William Wyler", isWinner: false, releaseYear: 1936 },
    { title: "Libeled Lady", director: "Jack Conway", isWinner: false, releaseYear: 1936 },
    { title: "Mr. Deeds Goes to Town", director: "Frank Capra", isWinner: false, releaseYear: 1936 },
    { title: "Romeo and Juliet", director: "George Cukor", isWinner: false, releaseYear: 1936 },
    { title: "San Francisco", director: "W.S. Van Dyke", isWinner: false, releaseYear: 1936 },
    { title: "The Story of Louis Pasteur", director: "William Dieterle", isWinner: false, releaseYear: 1936 },
    { title: "A Tale of Two Cities", director: "Jack Conway", isWinner: false, releaseYear: 1935 },
    { title: "Three Smart Girls", director: "Henry Koster", isWinner: false, releaseYear: 1936 },
  ],
  1938: [
    { title: "The Life of Emile Zola", director: "William Dieterle", isWinner: true, releaseYear: 1937 },
    { title: "The Awful Truth", director: "Leo McCarey", isWinner: false, releaseYear: 1937 },
    { title: "Captains Courageous", director: "Victor Fleming", isWinner: false, releaseYear: 1937 },
    { title: "Dead End", director: "William Wyler", isWinner: false, releaseYear: 1937 },
    { title: "The Good Earth", director: "Sidney Franklin", isWinner: false, releaseYear: 1937 },
    { title: "In Old Chicago", director: "Henry King", isWinner: false, releaseYear: 1937 },
    { title: "Lost Horizon", director: "Frank Capra", isWinner: false, releaseYear: 1937 },
    { title: "One Hundred Men and a Girl", director: "Henry Koster", isWinner: false, releaseYear: 1937 },
    { title: "Stage Door", director: "Gregory La Cava", isWinner: false, releaseYear: 1937 },
    { title: "A Star Is Born", director: "William A. Wellman", isWinner: false, releaseYear: 1937 },
  ],
  1939: [
    { title: "You Can't Take It with You", director: "Frank Capra", isWinner: true, releaseYear: 1938 },
    { title: "The Adventures of Robin Hood", director: "Michael Curtiz", isWinner: false, releaseYear: 1938 },
    { title: "Alexander's Ragtime Band", director: "Henry King", isWinner: false, releaseYear: 1938 },
    { title: "Boys Town", director: "Norman Taurog", isWinner: false, releaseYear: 1938 },
    { title: "The Citadel", director: "King Vidor", isWinner: false, releaseYear: 1938 },
    { title: "Four Daughters", director: "Michael Curtiz", isWinner: false, releaseYear: 1938 },
    { title: "Grand Illusion", director: "Jean Renoir", isWinner: false, releaseYear: 1937 },
    { title: "Jezebel", director: "William Wyler", isWinner: false, releaseYear: 1938 },
    { title: "Pygmalion", director: "Anthony Asquith", isWinner: false, releaseYear: 1938 },
    { title: "Test Pilot", director: "Victor Fleming", isWinner: false, releaseYear: 1938 },
  ],
  1940: [
    { title: "Gone with the Wind", director: "Victor Fleming", isWinner: true, releaseYear: 1939 },
    { title: "Dark Victory", director: "Edmund Goulding", isWinner: false, releaseYear: 1939 },
    { title: "Goodbye, Mr. Chips", director: "Sam Wood", isWinner: false, releaseYear: 1939 },
    { title: "Love Affair", director: "Leo McCarey", isWinner: false, releaseYear: 1939 },
    { title: "Mr. Smith Goes to Washington", director: "Frank Capra", isWinner: false, releaseYear: 1939 },
    { title: "Ninotchka", director: "Ernst Lubitsch", isWinner: false, releaseYear: 1939 },
    { title: "Of Mice and Men", director: "Lewis Milestone", isWinner: false, releaseYear: 1939 },
    { title: "Stagecoach", director: "John Ford", isWinner: false, releaseYear: 1939 },
    { title: "The Wizard of Oz", director: "Victor Fleming", isWinner: false, releaseYear: 1939 },
    { title: "Wuthering Heights", director: "William Wyler", isWinner: false, releaseYear: 1939 },
  ],
  1941: [
    { title: "Rebecca", director: "Alfred Hitchcock", isWinner: true, releaseYear: 1940 },
    { title: "All This, and Heaven Too", director: "Anatole Litvak", isWinner: false, releaseYear: 1940 },
    { title: "Foreign Correspondent", director: "Alfred Hitchcock", isWinner: false, releaseYear: 1940 },
    { title: "The Grapes of Wrath", director: "John Ford", isWinner: false, releaseYear: 1940 },
    { title: "The Great Dictator", director: "Charles Chaplin", isWinner: false, releaseYear: 1940 },
    { title: "Kitty Foyle", director: "Sam Wood", isWinner: false, releaseYear: 1940 },
    { title: "The Letter", director: "William Wyler", isWinner: false, releaseYear: 1940 },
    { title: "The Long Voyage Home", director: "John Ford", isWinner: false, releaseYear: 1940 },
    { title: "Our Town", director: "Sam Wood", isWinner: false, releaseYear: 1940 },
    { title: "The Philadelphia Story", director: "George Cukor", isWinner: false, releaseYear: 1940 },
  ],
  1942: [
    { title: "How Green Was My Valley", director: "John Ford", isWinner: true, releaseYear: 1941 },
    { title: "Blossoms in the Dust", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1941 },
    { title: "Citizen Kane", director: "Orson Welles", isWinner: false, releaseYear: 1941 },
    { title: "Here Comes Mr. Jordan", director: "Alexander Hall", isWinner: false, releaseYear: 1941 },
    { title: "Hold Back the Dawn", director: "Mitchell Leisen", isWinner: false, releaseYear: 1941 },
    { title: "The Little Foxes", director: "William Wyler", isWinner: false, releaseYear: 1941 },
    { title: "The Maltese Falcon", director: "John Huston", isWinner: false, releaseYear: 1941 },
    { title: "One Foot in Heaven", director: "Irving Rapper", isWinner: false, releaseYear: 1941 },
    { title: "Sergeant York", director: "Howard Hawks", isWinner: false, releaseYear: 1941 },
    { title: "Suspicion", director: "Alfred Hitchcock", isWinner: false, releaseYear: 1941 },
  ],
  1943: [
    { title: "Mrs. Miniver", director: "William Wyler", isWinner: true, releaseYear: 1942 },
    { title: "49th Parallel", director: "Michael Powell", isWinner: false, releaseYear: 1941 },
    { title: "Kings Row", director: "Sam Wood", isWinner: false, releaseYear: 1942 },
    { title: "The Magnificent Ambersons", director: "Orson Welles", isWinner: false, releaseYear: 1942 },
    { title: "The Pied Piper", director: "Irving Pichel", isWinner: false, releaseYear: 1942 },
    { title: "The Pride of the Yankees", director: "Sam Wood", isWinner: false, releaseYear: 1942 },
    { title: "Random Harvest", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1942 },
    { title: "The Talk of the Town", director: "George Stevens", isWinner: false, releaseYear: 1942 },
    { title: "Wake Island", director: "John Farrow", isWinner: false, releaseYear: 1942 },
    { title: "Yankee Doodle Dandy", director: "Michael Curtiz", isWinner: false, releaseYear: 1942 },
  ],
  1944: [
    { title: "Casablanca", director: "Michael Curtiz", isWinner: true, releaseYear: 1942 },
    { title: "For Whom the Bell Tolls", director: "Sam Wood", isWinner: false, releaseYear: 1943 },
    { title: "Heaven Can Wait", director: "Ernst Lubitsch", isWinner: false, releaseYear: 1943 },
    { title: "The Human Comedy", director: "Clarence Brown", isWinner: false, releaseYear: 1943 },
    { title: "In Which We Serve", director: "Noël Coward", isWinner: false, releaseYear: 1942 },
    { title: "Madame Curie", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1943 },
    { title: "The More the Merrier", director: "George Stevens", isWinner: false, releaseYear: 1943 },
    { title: "The Ox-Bow Incident", director: "William A. Wellman", isWinner: false, releaseYear: 1943 },
    { title: "The Song of Bernadette", director: "Henry King", isWinner: false, releaseYear: 1943 },
    { title: "Watch on the Rhine", director: "Herman Shumlin", isWinner: false, releaseYear: 1943 },
  ],
  1945: [
    { title: "Going My Way", director: "Leo McCarey", isWinner: true, releaseYear: 1944 },
    { title: "Double Indemnity", director: "Billy Wilder", isWinner: false, releaseYear: 1944 },
    { title: "Gaslight", director: "George Cukor", isWinner: false, releaseYear: 1944 },
    { title: "Since You Went Away", director: "John Cromwell", isWinner: false, releaseYear: 1944 },
    { title: "Wilson", director: "Henry King", isWinner: false, releaseYear: 1944 },
  ],
  1946: [
    { title: "The Lost Weekend", director: "Billy Wilder", isWinner: true, releaseYear: 1945 },
    { title: "Anchors Aweigh", director: "George Sidney", isWinner: false, releaseYear: 1945 },
    { title: "The Bells of St. Mary's", director: "Leo McCarey", isWinner: false, releaseYear: 1945 },
    { title: "Mildred Pierce", director: "Michael Curtiz", isWinner: false, releaseYear: 1945 },
    { title: "Spellbound", director: "Alfred Hitchcock", isWinner: false, releaseYear: 1945 },
  ],
  1947: [
    { title: "The Best Years of Our Lives", director: "William Wyler", isWinner: true, releaseYear: 1946 },
    { title: "Henry V", director: "Laurence Olivier", isWinner: false, releaseYear: 1944 },
    { title: "It's a Wonderful Life", director: "Frank Capra", isWinner: false, releaseYear: 1946 },
    { title: "The Razor's Edge", director: "Edmund Goulding", isWinner: false, releaseYear: 1946 },
    { title: "The Yearling", director: "Clarence Brown", isWinner: false, releaseYear: 1946 },
  ],
  1948: [
    { title: "Gentleman's Agreement", director: "Elia Kazan", isWinner: true, releaseYear: 1947 },
    { title: "The Bishop's Wife", director: "Henry Koster", isWinner: false, releaseYear: 1947 },
    { title: "Crossfire", director: "Edward Dmytryk", isWinner: false, releaseYear: 1947 },
    { title: "Great Expectations", director: "David Lean", isWinner: false, releaseYear: 1946 },
    { title: "Miracle on 34th Street", director: "George Seaton", isWinner: false, releaseYear: 1947 },
  ],
  1949: [
    { title: "Hamlet", director: "Laurence Olivier", isWinner: true, releaseYear: 1948 },
    { title: "Johnny Belinda", director: "Jean Negulesco", isWinner: false, releaseYear: 1948 },
    { title: "The Red Shoes", director: "Michael Powell", isWinner: false, releaseYear: 1948 },
    { title: "The Snake Pit", director: "Anatole Litvak", isWinner: false, releaseYear: 1948 },
    { title: "The Treasure of the Sierra Madre", director: "John Huston", isWinner: false, releaseYear: 1948 },
  ],
  1950: [
    { title: "All the King's Men", director: "Robert Rossen", isWinner: true, releaseYear: 1949 },
    { title: "Battleground", director: "William A. Wellman", isWinner: false, releaseYear: 1949 },
    { title: "The Heiress", director: "William Wyler", isWinner: false, releaseYear: 1949 },
    { title: "A Letter to Three Wives", director: "Joseph L. Mankiewicz", isWinner: false, releaseYear: 1949 },
    { title: "Twelve O'Clock High", director: "Henry King", isWinner: false, releaseYear: 1949 },
  ],
  1951: [
    { title: "All About Eve", director: "Joseph L. Mankiewicz", isWinner: true, releaseYear: 1950 },
    { title: "Born Yesterday", director: "George Cukor", isWinner: false, releaseYear: 1950 },
    { title: "Father of the Bride", director: "Vincente Minnelli", isWinner: false, releaseYear: 1950 },
    { title: "King Solomon's Mines", director: "Compton Bennett", isWinner: false, releaseYear: 1950 },
    { title: "Sunset Boulevard", director: "Billy Wilder", isWinner: false, releaseYear: 1950 },
  ],
  1952: [
    { title: "An American in Paris", director: "Vincente Minnelli", isWinner: true, releaseYear: 1951 },
    { title: "Decision Before Dawn", director: "Anatole Litvak", isWinner: false, releaseYear: 1951 },
    { title: "A Place in the Sun", director: "George Stevens", isWinner: false, releaseYear: 1951 },
    { title: "Quo Vadis", director: "Mervyn LeRoy", isWinner: false, releaseYear: 1951 },
    { title: "A Streetcar Named Desire", director: "Elia Kazan", isWinner: false, releaseYear: 1951 },
  ],
  1953: [
    { title: "The Greatest Show on Earth", director: "Cecil B. DeMille", isWinner: true, releaseYear: 1952 },
    { title: "High Noon", director: "Fred Zinnemann", isWinner: false, releaseYear: 1952 },
    { title: "Ivanhoe", director: "Richard Thorpe", isWinner: false, releaseYear: 1952 },
    { title: "Moulin Rouge", director: "John Huston", isWinner: false, releaseYear: 1952 },
    { title: "The Quiet Man", director: "John Ford", isWinner: false, releaseYear: 1952 },
  ],
  1954: [
    { title: "From Here to Eternity", director: "Fred Zinnemann", isWinner: true, releaseYear: 1953 },
    { title: "Julius Caesar", director: "Joseph L. Mankiewicz", isWinner: false, releaseYear: 1953 },
    { title: "The Robe", director: "Henry Koster", isWinner: false, releaseYear: 1953 },
    { title: "Roman Holiday", director: "William Wyler", isWinner: false, releaseYear: 1953 },
    { title: "Shane", director: "George Stevens", isWinner: false, releaseYear: 1953 },
  ],
  1955: [
    { title: "On the Waterfront", director: "Elia Kazan", isWinner: true, releaseYear: 1954 },
    { title: "The Caine Mutiny", director: "Edward Dmytryk", isWinner: false, releaseYear: 1954 },
    { title: "The Country Girl", director: "George Seaton", isWinner: false, releaseYear: 1954 },
    { title: "Seven Brides for Seven Brothers", director: "Stanley Donen", isWinner: false, releaseYear: 1954 },
    { title: "Three Coins in the Fountain", director: "Jean Negulesco", isWinner: false, releaseYear: 1954 },
  ],
  1956: [
    { title: "Marty", director: "Delbert Mann", isWinner: true, releaseYear: 1955 },
    { title: "Love Is a Many-Splendored Thing", director: "Henry King", isWinner: false, releaseYear: 1955 },
    { title: "Mister Roberts", director: "John Ford", isWinner: false, releaseYear: 1955 },
    { title: "Picnic", director: "Joshua Logan", isWinner: false, releaseYear: 1955 },
    { title: "The Rose Tattoo", director: "Daniel Mann", isWinner: false, releaseYear: 1955 },
  ],
  1957: [
    { title: "Around the World in 80 Days", director: "Michael Anderson", isWinner: true, releaseYear: 1956 },
    { title: "Friendly Persuasion", director: "William Wyler", isWinner: false, releaseYear: 1956 },
    { title: "Giant", director: "George Stevens", isWinner: false, releaseYear: 1956 },
    { title: "The King and I", director: "Walter Lang", isWinner: false, releaseYear: 1956 },
    { title: "The Ten Commandments", director: "Cecil B. DeMille", isWinner: false, releaseYear: 1956 },
  ],
  1958: [
    { title: "The Bridge on the River Kwai", director: "David Lean", isWinner: true, releaseYear: 1957 },
    { title: "12 Angry Men", director: "Sidney Lumet", isWinner: false, releaseYear: 1957 },
    { title: "Peyton Place", director: "Mark Robson", isWinner: false, releaseYear: 1957 },
    { title: "Sayonara", director: "Joshua Logan", isWinner: false, releaseYear: 1957 },
    { title: "Witness for the Prosecution", director: "Billy Wilder", isWinner: false, releaseYear: 1957 },
  ],
  1959: [
    { title: "Gigi", director: "Vincente Minnelli", isWinner: true, releaseYear: 1958 },
    { title: "Auntie Mame", director: "Morton DaCosta", isWinner: false, releaseYear: 1958 },
    { title: "Cat on a Hot Tin Roof", director: "Richard Brooks", isWinner: false, releaseYear: 1958 },
    { title: "The Defiant Ones", director: "Stanley Kramer", isWinner: false, releaseYear: 1958 },
    { title: "Separate Tables", director: "Delbert Mann", isWinner: false, releaseYear: 1958 },
  ],
  1960: [
    { title: "Ben-Hur", director: "William Wyler", isWinner: true, releaseYear: 1959 },
    { title: "Anatomy of a Murder", director: "Otto Preminger", isWinner: false, releaseYear: 1959 },
    { title: "The Diary of Anne Frank", director: "George Stevens", isWinner: false, releaseYear: 1959 },
    { title: "The Nun's Story", director: "Fred Zinnemann", isWinner: false, releaseYear: 1959 },
    { title: "Room at the Top", director: "Jack Clayton", isWinner: false, releaseYear: 1959 },
  ],
  1961: [
    { title: "The Apartment", director: "Billy Wilder", isWinner: true, releaseYear: 1960 },
    { title: "The Alamo", director: "John Wayne", isWinner: false, releaseYear: 1960 },
    { title: "Elmer Gantry", director: "Richard Brooks", isWinner: false, releaseYear: 1960 },
    { title: "Sons and Lovers", director: "Jack Cardiff", isWinner: false, releaseYear: 1960 },
    { title: "The Sundowners", director: "Fred Zinnemann", isWinner: false, releaseYear: 1960 },
  ],
  1962: [
    { title: "West Side Story", director: "Robert Wise", isWinner: true, releaseYear: 1961 },
    { title: "Fanny", director: "Joshua Logan", isWinner: false, releaseYear: 1961 },
    { title: "The Guns of Navarone", director: "J. Lee Thompson", isWinner: false, releaseYear: 1961 },
    { title: "The Hustler", director: "Robert Rossen", isWinner: false, releaseYear: 1961 },
    { title: "Judgment at Nuremberg", director: "Stanley Kramer", isWinner: false, releaseYear: 1961 },
  ],
  1963: [
    { title: "Lawrence of Arabia", director: "David Lean", isWinner: true, releaseYear: 1962 },
    { title: "The Longest Day", director: "Ken Annakin", isWinner: false, releaseYear: 1962 },
    { title: "The Music Man", director: "Morton DaCosta", isWinner: false, releaseYear: 1962 },
    { title: "Mutiny on the Bounty", director: "Lewis Milestone", isWinner: false, releaseYear: 1962 },
    { title: "To Kill a Mockingbird", director: "Robert Mulligan", isWinner: false, releaseYear: 1962 },
  ],
  1964: [
    { title: "Tom Jones", director: "Tony Richardson", isWinner: true, releaseYear: 1963 },
    { title: "America, America", director: "Elia Kazan", isWinner: false, releaseYear: 1963 },
    { title: "Cleopatra", director: "Joseph L. Mankiewicz", isWinner: false, releaseYear: 1963 },
    { title: "How the West Was Won", director: "Henry Hathaway", isWinner: false, releaseYear: 1962 },
    { title: "Lilies of the Field", director: "Ralph Nelson", isWinner: false, releaseYear: 1963 },
  ],
  1965: [
    { title: "My Fair Lady", director: "George Cukor", isWinner: true, releaseYear: 1964 },
    { title: "Becket", director: "Peter Glenville", isWinner: false, releaseYear: 1964 },
    { title: "Dr. Strangelove", director: "Stanley Kubrick", isWinner: false, releaseYear: 1964 },
    { title: "Mary Poppins", director: "Robert Stevenson", isWinner: false, releaseYear: 1964 },
    { title: "Zorba the Greek", director: "Michael Cacoyannis", isWinner: false, releaseYear: 1964 },
  ],
  1966: [
    { title: "The Sound of Music", director: "Robert Wise", isWinner: true, releaseYear: 1965 },
    { title: "Darling", director: "John Schlesinger", isWinner: false, releaseYear: 1965 },
    { title: "Doctor Zhivago", director: "David Lean", isWinner: false, releaseYear: 1965 },
    { title: "Ship of Fools", director: "Stanley Kramer", isWinner: false, releaseYear: 1965 },
    { title: "A Thousand Clowns", director: "Fred Coe", isWinner: false, releaseYear: 1965 },
  ],
  1967: [
    { title: "A Man for All Seasons", director: "Fred Zinnemann", isWinner: true, releaseYear: 1966 },
    { title: "Alfie", director: "Lewis Gilbert", isWinner: false, releaseYear: 1966 },
    { title: "The Russians Are Coming, the Russians Are Coming", director: "Norman Jewison", isWinner: false, releaseYear: 1966 },
    { title: "The Sand Pebbles", director: "Robert Wise", isWinner: false, releaseYear: 1966 },
    { title: "Who's Afraid of Virginia Woolf?", director: "Mike Nichols", isWinner: false, releaseYear: 1966 },
  ],
  1968: [
    { title: "In the Heat of the Night", director: "Norman Jewison", isWinner: true, releaseYear: 1967 },
    { title: "Bonnie and Clyde", director: "Arthur Penn", isWinner: false, releaseYear: 1967 },
    { title: "Doctor Dolittle", director: "Richard Fleischer", isWinner: false, releaseYear: 1967 },
    { title: "The Graduate", director: "Mike Nichols", isWinner: false, releaseYear: 1967 },
    { title: "Guess Who's Coming to Dinner", director: "Stanley Kramer", isWinner: false, releaseYear: 1967 },
  ],
  1969: [
    { title: "Oliver!", director: "Carol Reed", isWinner: true, releaseYear: 1968 },
    { title: "Funny Girl", director: "William Wyler", isWinner: false, releaseYear: 1968 },
    { title: "The Lion in Winter", director: "Anthony Harvey", isWinner: false, releaseYear: 1968 },
    { title: "Rachel, Rachel", director: "Paul Newman", isWinner: false, releaseYear: 1968 },
    { title: "Romeo and Juliet", director: "Franco Zeffirelli", isWinner: false, releaseYear: 1968 },
  ],
  1970: [
    { title: "Midnight Cowboy", director: "John Schlesinger", isWinner: true, releaseYear: 1969 },
    { title: "Anne of the Thousand Days", director: "Charles Jarrott", isWinner: false, releaseYear: 1969 },
    { title: "Butch Cassidy and the Sundance Kid", director: "George Roy Hill", isWinner: false, releaseYear: 1969 },
    { title: "Hello, Dolly!", director: "Gene Kelly", isWinner: false, releaseYear: 1969 },
    { title: "Z", director: "Costa-Gavras", isWinner: false, releaseYear: 1969 },
  ],
  1971: [
    { title: "Patton", director: "Franklin J. Schaffner", isWinner: true, releaseYear: 1970 },
    { title: "Airport", director: "George Seaton", isWinner: false, releaseYear: 1970 },
    { title: "Five Easy Pieces", director: "Bob Rafelson", isWinner: false, releaseYear: 1970 },
    { title: "Love Story", director: "Arthur Hiller", isWinner: false, releaseYear: 1970 },
    { title: "MASH", director: "Robert Altman", isWinner: false, releaseYear: 1970 },
  ],
  1972: [
    { title: "The French Connection", director: "William Friedkin", isWinner: true, releaseYear: 1971 },
    { title: "A Clockwork Orange", director: "Stanley Kubrick", isWinner: false, releaseYear: 1971 },
    { title: "Fiddler on the Roof", director: "Norman Jewison", isWinner: false, releaseYear: 1971 },
    { title: "The Last Picture Show", director: "Peter Bogdanovich", isWinner: false, releaseYear: 1971 },
    { title: "Nicholas and Alexandra", director: "Franklin J. Schaffner", isWinner: false, releaseYear: 1971 },
  ],
  1973: [
    { title: "The Godfather", director: "Francis Ford Coppola", isWinner: true, releaseYear: 1972 },
    { title: "Cabaret", director: "Bob Fosse", isWinner: false, releaseYear: 1972 },
    { title: "Deliverance", director: "John Boorman", isWinner: false, releaseYear: 1972 },
    { title: "The Emigrants", director: "Jan Troell", isWinner: false, releaseYear: 1971 },
    { title: "Sounder", director: "Martin Ritt", isWinner: false, releaseYear: 1972 },
  ],
  1974: [
    { title: "The Sting", director: "George Roy Hill", isWinner: true, releaseYear: 1973 },
    { title: "American Graffiti", director: "George Lucas", isWinner: false, releaseYear: 1973 },
    { title: "Cries and Whispers", director: "Ingmar Bergman", isWinner: false, releaseYear: 1972 },
    { title: "The Exorcist", director: "William Friedkin", isWinner: false, releaseYear: 1973 },
    { title: "A Touch of Class", director: "Melvin Frank", isWinner: false, releaseYear: 1973 },
  ],
  1975: [
    { title: "The Godfather Part II", director: "Francis Ford Coppola", isWinner: true, releaseYear: 1974 },
    { title: "Chinatown", director: "Roman Polanski", isWinner: false, releaseYear: 1974 },
    { title: "The Conversation", director: "Francis Ford Coppola", isWinner: false, releaseYear: 1974 },
    { title: "Lenny", director: "Bob Fosse", isWinner: false, releaseYear: 1974 },
    { title: "The Towering Inferno", director: "John Guillermin", isWinner: false, releaseYear: 1974 },
  ],
  1976: [
    { title: "One Flew Over the Cuckoo's Nest", director: "Miloš Forman", isWinner: true, releaseYear: 1975 },
    { title: "Barry Lyndon", director: "Stanley Kubrick", isWinner: false, releaseYear: 1975 },
    { title: "Dog Day Afternoon", director: "Sidney Lumet", isWinner: false, releaseYear: 1975 },
    { title: "Jaws", director: "Steven Spielberg", isWinner: false, releaseYear: 1975 },
    { title: "Nashville", director: "Robert Altman", isWinner: false, releaseYear: 1975 },
  ],
  1977: [
    { title: "Rocky", director: "John G. Avildsen", isWinner: true, releaseYear: 1976 },
    { title: "All the President's Men", director: "Alan J. Pakula", isWinner: false, releaseYear: 1976 },
    { title: "Bound for Glory", director: "Hal Ashby", isWinner: false, releaseYear: 1976 },
    { title: "Network", director: "Sidney Lumet", isWinner: false, releaseYear: 1976 },
    { title: "Taxi Driver", director: "Martin Scorsese", isWinner: false, releaseYear: 1976 },
  ],
  1978: [
    { title: "Annie Hall", director: "Woody Allen", isWinner: true, releaseYear: 1977 },
    { title: "The Goodbye Girl", director: "Herbert Ross", isWinner: false, releaseYear: 1977 },
    { title: "Julia", director: "Fred Zinnemann", isWinner: false, releaseYear: 1977 },
    { title: "Star Wars", director: "George Lucas", isWinner: false, releaseYear: 1977 },
    { title: "The Turning Point", director: "Herbert Ross", isWinner: false, releaseYear: 1977 },
  ],
  1979: [
    { title: "The Deer Hunter", director: "Michael Cimino", isWinner: true, releaseYear: 1978 },
    { title: "Coming Home", director: "Hal Ashby", isWinner: false, releaseYear: 1978 },
    { title: "Heaven Can Wait", director: "Warren Beatty", isWinner: false, releaseYear: 1978 },
    { title: "An Unmarried Woman", director: "Paul Mazursky", isWinner: false, releaseYear: 1978 },
    { title: "Midnight Express", director: "Alan Parker", isWinner: false, releaseYear: 1978 },
  ],
  1980: [
    { title: "Kramer vs. Kramer", director: "Robert Benton", isWinner: true, releaseYear: 1979 },
    { title: "All That Jazz", director: "Bob Fosse", isWinner: false, releaseYear: 1979 },
    { title: "Apocalypse Now", director: "Francis Ford Coppola", isWinner: false, releaseYear: 1979 },
    { title: "Breaking Away", director: "Peter Yates", isWinner: false, releaseYear: 1979 },
    { title: "Norma Rae", director: "Martin Ritt", isWinner: false, releaseYear: 1979 },
  ],
  1981: [
    { title: "Ordinary People", director: "Robert Redford", isWinner: true, releaseYear: 1980 },
    { title: "Coal Miner's Daughter", director: "Michael Apted", isWinner: false, releaseYear: 1980 },
    { title: "The Elephant Man", director: "David Lynch", isWinner: false, releaseYear: 1980 },
    { title: "Raging Bull", director: "Martin Scorsese", isWinner: false, releaseYear: 1980 },
    { title: "Tess", director: "Roman Polanski", isWinner: false, releaseYear: 1979 },
  ],
  1982: [
    { title: "Chariots of Fire", director: "Hugh Hudson", isWinner: true, releaseYear: 1981 },
    { title: "Atlantic City", director: "Louis Malle", isWinner: false, releaseYear: 1980 },
    { title: "On Golden Pond", director: "Mark Rydell", isWinner: false, releaseYear: 1981 },
    { title: "Raiders of the Lost Ark", director: "Steven Spielberg", isWinner: false, releaseYear: 1981 },
    { title: "Reds", director: "Warren Beatty", isWinner: false, releaseYear: 1981 },
  ],
  1983: [
    { title: "Gandhi", director: "Richard Attenborough", isWinner: true, releaseYear: 1982 },
    { title: "E.T. the Extra-Terrestrial", director: "Steven Spielberg", isWinner: false, releaseYear: 1982 },
    { title: "Missing", director: "Costa-Gavras", isWinner: false, releaseYear: 1982 },
    { title: "Tootsie", director: "Sydney Pollack", isWinner: false, releaseYear: 1982 },
    { title: "The Verdict", director: "Sidney Lumet", isWinner: false, releaseYear: 1982 },
  ],
  1984: [
    { title: "Terms of Endearment", director: "James L. Brooks", isWinner: true, releaseYear: 1983 },
    { title: "The Big Chill", director: "Lawrence Kasdan", isWinner: false, releaseYear: 1983 },
    { title: "The Dresser", director: "Peter Yates", isWinner: false, releaseYear: 1983 },
    { title: "The Right Stuff", director: "Philip Kaufman", isWinner: false, releaseYear: 1983 },
    { title: "Tender Mercies", director: "Bruce Beresford", isWinner: false, releaseYear: 1983 },
  ],
  1985: [
    { title: "Amadeus", director: "Miloš Forman", isWinner: true, releaseYear: 1984 },
    { title: "The Killing Fields", director: "Roland Joffé", isWinner: false, releaseYear: 1984 },
    { title: "A Passage to India", director: "David Lean", isWinner: false, releaseYear: 1984 },
    { title: "Places in the Heart", director: "Robert Benton", isWinner: false, releaseYear: 1984 },
    { title: "A Soldier's Story", director: "Norman Jewison", isWinner: false, releaseYear: 1984 },
  ],
  1986: [
    { title: "Out of Africa", director: "Sydney Pollack", isWinner: true, releaseYear: 1985 },
    { title: "The Color Purple", director: "Steven Spielberg", isWinner: false, releaseYear: 1985 },
    { title: "Kiss of the Spider Woman", director: "Héctor Babenco", isWinner: false, releaseYear: 1985 },
    { title: "Prizzi's Honor", director: "John Huston", isWinner: false, releaseYear: 1985 },
    { title: "Witness", director: "Peter Weir", isWinner: false, releaseYear: 1985 },
  ],
  1987: [
    { title: "Platoon", director: "Oliver Stone", isWinner: true, releaseYear: 1986 },
    { title: "Children of a Lesser God", director: "Randa Haines", isWinner: false, releaseYear: 1986 },
    { title: "Hannah and Her Sisters", director: "Woody Allen", isWinner: false, releaseYear: 1986 },
    { title: "The Mission", director: "Roland Joffé", isWinner: false, releaseYear: 1986 },
    { title: "A Room with a View", director: "James Ivory", isWinner: false, releaseYear: 1985 },
  ],
  1988: [
    { title: "The Last Emperor", director: "Bernardo Bertolucci", isWinner: true, releaseYear: 1987 },
    { title: "Broadcast News", director: "James L. Brooks", isWinner: false, releaseYear: 1987 },
    { title: "Fatal Attraction", director: "Adrian Lyne", isWinner: false, releaseYear: 1987 },
    { title: "Hope and Glory", director: "John Boorman", isWinner: false, releaseYear: 1987 },
    { title: "Moonstruck", director: "Norman Jewison", isWinner: false, releaseYear: 1987 },
  ],
  1989: [
    { title: "Rain Man", director: "Barry Levinson", isWinner: true, releaseYear: 1988 },
    { title: "The Accidental Tourist", director: "Lawrence Kasdan", isWinner: false, releaseYear: 1988 },
    { title: "Dangerous Liaisons", director: "Stephen Frears", isWinner: false, releaseYear: 1988 },
    { title: "Mississippi Burning", director: "Alan Parker", isWinner: false, releaseYear: 1988 },
    { title: "Working Girl", director: "Mike Nichols", isWinner: false, releaseYear: 1988 },
  ],
  1990: [
    { title: "Driving Miss Daisy", director: "Bruce Beresford", isWinner: true, releaseYear: 1989 },
    { title: "Born on the Fourth of July", director: "Oliver Stone", isWinner: false, releaseYear: 1989 },
    { title: "Dead Poets Society", director: "Peter Weir", isWinner: false, releaseYear: 1989 },
    { title: "Field of Dreams", director: "Phil Alden Robinson", isWinner: false, releaseYear: 1989 },
    { title: "My Left Foot", director: "Jim Sheridan", isWinner: false, releaseYear: 1989 },
  ],
  1991: [
    { title: "Dances with Wolves", director: "Kevin Costner", isWinner: true, releaseYear: 1990 },
    { title: "Awakenings", director: "Penny Marshall", isWinner: false, releaseYear: 1990 },
    { title: "Ghost", director: "Jerry Zucker", isWinner: false, releaseYear: 1990 },
    { title: "The Godfather Part III", director: "Francis Ford Coppola", isWinner: false, releaseYear: 1990 },
    { title: "GoodFellas", director: "Martin Scorsese", isWinner: false, releaseYear: 1990 },
  ],
  1992: [
    { title: "The Silence of the Lambs", director: "Jonathan Demme", isWinner: true, releaseYear: 1991 },
    { title: "Beauty and the Beast", director: "Gary Trousdale & Kirk Wise", isWinner: false, releaseYear: 1991 },
    { title: "Bugsy", director: "Barry Levinson", isWinner: false, releaseYear: 1991 },
    { title: "JFK", director: "Oliver Stone", isWinner: false, releaseYear: 1991 },
    { title: "The Prince of Tides", director: "Barbra Streisand", isWinner: false, releaseYear: 1991 },
  ],
  1993: [
    { title: "Unforgiven", director: "Clint Eastwood", isWinner: true, releaseYear: 1992 },
    { title: "The Crying Game", director: "Neil Jordan", isWinner: false, releaseYear: 1992 },
    { title: "A Few Good Men", director: "Rob Reiner", isWinner: false, releaseYear: 1992 },
    { title: "Howards End", director: "James Ivory", isWinner: false, releaseYear: 1992 },
    { title: "Scent of a Woman", director: "Martin Brest", isWinner: false, releaseYear: 1992 },
  ],
  1994: [
    { title: "Schindler's List", director: "Steven Spielberg", isWinner: true, releaseYear: 1993 },
    { title: "The Fugitive", director: "Andrew Davis", isWinner: false, releaseYear: 1993 },
    { title: "In the Name of the Father", director: "Jim Sheridan", isWinner: false, releaseYear: 1993 },
    { title: "The Piano", director: "Jane Campion", isWinner: false, releaseYear: 1993 },
    { title: "The Remains of the Day", director: "James Ivory", isWinner: false, releaseYear: 1993 },
  ],
  1995: [
    { title: "Forrest Gump", director: "Robert Zemeckis", isWinner: true, releaseYear: 1994 },
    { title: "Four Weddings and a Funeral", director: "Mike Newell", isWinner: false, releaseYear: 1994 },
    { title: "Pulp Fiction", director: "Quentin Tarantino", isWinner: false, releaseYear: 1994 },
    { title: "Quiz Show", director: "Robert Redford", isWinner: false, releaseYear: 1994 },
    { title: "The Shawshank Redemption", director: "Frank Darabont", isWinner: false, releaseYear: 1994 },
  ],
  1996: [
    { title: "Braveheart", director: "Mel Gibson", isWinner: true, releaseYear: 1995 },
    { title: "Apollo 13", director: "Ron Howard", isWinner: false, releaseYear: 1995 },
    { title: "Babe", director: "Chris Noonan", isWinner: false, releaseYear: 1995 },
    { title: "Il Postino", director: "Michael Radford", isWinner: false, releaseYear: 1994 },
    { title: "Sense and Sensibility", director: "Ang Lee", isWinner: false, releaseYear: 1995 },
  ],
  1997: [
    { title: "The English Patient", director: "Anthony Minghella", isWinner: true, releaseYear: 1996 },
    { title: "Fargo", director: "Joel Coen", isWinner: false, releaseYear: 1996 },
    { title: "Jerry Maguire", director: "Cameron Crowe", isWinner: false, releaseYear: 1996 },
    { title: "Secrets & Lies", director: "Mike Leigh", isWinner: false, releaseYear: 1996 },
    { title: "Shine", director: "Scott Hicks", isWinner: false, releaseYear: 1996 },
  ],
  1998: [
    { title: "Titanic", director: "James Cameron", isWinner: true, releaseYear: 1997 },
    { title: "As Good as It Gets", director: "James L. Brooks", isWinner: false, releaseYear: 1997 },
    { title: "The Full Monty", director: "Peter Cattaneo", isWinner: false, releaseYear: 1997 },
    { title: "Good Will Hunting", director: "Gus Van Sant", isWinner: false, releaseYear: 1997 },
    { title: "L.A. Confidential", director: "Curtis Hanson", isWinner: false, releaseYear: 1997 },
  ],
  1999: [
    { title: "Shakespeare in Love", director: "John Madden", isWinner: true, releaseYear: 1998 },
    { title: "Elizabeth", director: "Shekhar Kapur", isWinner: false, releaseYear: 1998 },
    { title: "Life Is Beautiful", director: "Roberto Benigni", isWinner: false, releaseYear: 1997 },
    { title: "Saving Private Ryan", director: "Steven Spielberg", isWinner: false, releaseYear: 1998 },
    { title: "The Thin Red Line", director: "Terrence Malick", isWinner: false, releaseYear: 1998 },
  ],
  2000: [
    { title: "American Beauty", director: "Sam Mendes", isWinner: true, releaseYear: 1999 },
    { title: "The Cider House Rules", director: "Lasse Hallström", isWinner: false, releaseYear: 1999 },
    { title: "The Green Mile", director: "Frank Darabont", isWinner: false, releaseYear: 1999 },
    { title: "The Insider", director: "Michael Mann", isWinner: false, releaseYear: 1999 },
    { title: "The Sixth Sense", director: "M. Night Shyamalan", isWinner: false, releaseYear: 1999 },
  ],
  2001: [
    { title: "Gladiator", director: "Ridley Scott", isWinner: true, releaseYear: 2000 },
    { title: "Chocolat", director: "Lasse Hallström", isWinner: false, releaseYear: 2000 },
    { title: "Crouching Tiger, Hidden Dragon", director: "Ang Lee", isWinner: false, releaseYear: 2000 },
    { title: "Erin Brockovich", director: "Steven Soderbergh", isWinner: false, releaseYear: 2000 },
    { title: "Traffic", director: "Steven Soderbergh", isWinner: false, releaseYear: 2000 },
  ],
  2002: [
    { title: "A Beautiful Mind", director: "Ron Howard", isWinner: true, releaseYear: 2001 },
    { title: "Gosford Park", director: "Robert Altman", isWinner: false, releaseYear: 2001 },
    { title: "In the Bedroom", director: "Todd Field", isWinner: false, releaseYear: 2001 },
    { title: "The Lord of the Rings: The Fellowship of the Ring", director: "Peter Jackson", isWinner: false, releaseYear: 2001 },
    { title: "Moulin Rouge!", director: "Baz Luhrmann", isWinner: false, releaseYear: 2001 },
  ],
  2003: [
    { title: "Chicago", director: "Rob Marshall", isWinner: true, releaseYear: 2002 },
    { title: "Gangs of New York", director: "Martin Scorsese", isWinner: false, releaseYear: 2002 },
    { title: "The Hours", director: "Stephen Daldry", isWinner: false, releaseYear: 2002 },
    { title: "The Lord of the Rings: The Two Towers", director: "Peter Jackson", isWinner: false, releaseYear: 2002 },
    { title: "The Pianist", director: "Roman Polanski", isWinner: false, releaseYear: 2002 },
  ],
  2004: [
    { title: "The Lord of the Rings: The Return of the King", director: "Peter Jackson", isWinner: true, releaseYear: 2003 },
    { title: "Lost in Translation", director: "Sofia Coppola", isWinner: false, releaseYear: 2003 },
    { title: "Master and Commander: The Far Side of the World", director: "Peter Weir", isWinner: false, releaseYear: 2003 },
    { title: "Mystic River", director: "Clint Eastwood", isWinner: false, releaseYear: 2003 },
    { title: "Seabiscuit", director: "Gary Ross", isWinner: false, releaseYear: 2003 },
  ],
  2005: [
    { title: "Million Dollar Baby", director: "Clint Eastwood", isWinner: true, releaseYear: 2004 },
    { title: "The Aviator", director: "Martin Scorsese", isWinner: false, releaseYear: 2004 },
    { title: "Finding Neverland", director: "Marc Forster", isWinner: false, releaseYear: 2004 },
    { title: "Ray", director: "Taylor Hackford", isWinner: false, releaseYear: 2004 },
    { title: "Sideways", director: "Alexander Payne", isWinner: false, releaseYear: 2004 },
  ],
  2006: [
    { title: "Crash", director: "Paul Haggis", isWinner: true, releaseYear: 2004 },
    { title: "Brokeback Mountain", director: "Ang Lee", isWinner: false, releaseYear: 2005 },
    { title: "Capote", director: "Bennett Miller", isWinner: false, releaseYear: 2005 },
    { title: "Good Night, and Good Luck", director: "George Clooney", isWinner: false, releaseYear: 2005 },
    { title: "Munich", director: "Steven Spielberg", isWinner: false, releaseYear: 2005 },
  ],
  2007: [
    { title: "The Departed", director: "Martin Scorsese", isWinner: true, releaseYear: 2006 },
    { title: "Babel", director: "Alejandro González Iñárritu", isWinner: false, releaseYear: 2006 },
    { title: "Letters from Iwo Jima", director: "Clint Eastwood", isWinner: false, releaseYear: 2006 },
    { title: "Little Miss Sunshine", director: "Jonathan Dayton & Valerie Faris", isWinner: false, releaseYear: 2006 },
    { title: "The Queen", director: "Stephen Frears", isWinner: false, releaseYear: 2006 },
  ],
  2008: [
    { title: "No Country for Old Men", director: "Joel Coen & Ethan Coen", isWinner: true, releaseYear: 2007 },
    { title: "Atonement", director: "Joe Wright", isWinner: false, releaseYear: 2007 },
    { title: "Juno", director: "Jason Reitman", isWinner: false, releaseYear: 2007 },
    { title: "Michael Clayton", director: "Tony Gilroy", isWinner: false, releaseYear: 2007 },
    { title: "There Will Be Blood", director: "Paul Thomas Anderson", isWinner: false, releaseYear: 2007 },
  ],
  2009: [
    { title: "Slumdog Millionaire", director: "Danny Boyle", isWinner: true, releaseYear: 2008 },
    { title: "The Curious Case of Benjamin Button", director: "David Fincher", isWinner: false, releaseYear: 2008 },
    { title: "Frost/Nixon", director: "Ron Howard", isWinner: false, releaseYear: 2008 },
    { title: "Milk", director: "Gus Van Sant", isWinner: false, releaseYear: 2008 },
    { title: "The Reader", director: "Stephen Daldry", isWinner: false, releaseYear: 2008 },
  ],
  2010: [
    { title: "The Hurt Locker", director: "Kathryn Bigelow", isWinner: true, releaseYear: 2008 },
    { title: "Avatar", director: "James Cameron", isWinner: false, releaseYear: 2009 },
    { title: "The Blind Side", director: "John Lee Hancock", isWinner: false, releaseYear: 2009 },
    { title: "District 9", director: "Neill Blomkamp", isWinner: false, releaseYear: 2009 },
    { title: "An Education", director: "Lone Scherfig", isWinner: false, releaseYear: 2009 },
    { title: "Inglourious Basterds", director: "Quentin Tarantino", isWinner: false, releaseYear: 2009 },
    { title: "Precious", director: "Lee Daniels", isWinner: false, releaseYear: 2009 },
    { title: "A Serious Man", director: "Joel Coen & Ethan Coen", isWinner: false, releaseYear: 2009 },
    { title: "Up", director: "Pete Docter", isWinner: false, releaseYear: 2009 },
    { title: "Up in the Air", director: "Jason Reitman", isWinner: false, releaseYear: 2009 },
  ],
  2011: [
    { title: "The King's Speech", director: "Tom Hooper", isWinner: true, releaseYear: 2010 },
    { title: "127 Hours", director: "Danny Boyle", isWinner: false, releaseYear: 2010 },
    { title: "Black Swan", director: "Darren Aronofsky", isWinner: false, releaseYear: 2010 },
    { title: "The Fighter", director: "David O. Russell", isWinner: false, releaseYear: 2010 },
    { title: "Inception", director: "Christopher Nolan", isWinner: false, releaseYear: 2010 },
    { title: "The Kids Are All Right", director: "Lisa Cholodenko", isWinner: false, releaseYear: 2010 },
    { title: "The Social Network", director: "David Fincher", isWinner: false, releaseYear: 2010 },
    { title: "Toy Story 3", director: "Lee Unkrich", isWinner: false, releaseYear: 2010 },
    { title: "True Grit", director: "Joel Coen & Ethan Coen", isWinner: false, releaseYear: 2010 },
    { title: "Winter's Bone", director: "Debra Granik", isWinner: false, releaseYear: 2010 },
  ],
  2012: [
    { title: "The Artist", director: "Michel Hazanavicius", isWinner: true, releaseYear: 2011 },
    { title: "The Descendants", director: "Alexander Payne", isWinner: false, releaseYear: 2011 },
    { title: "Extremely Loud & Incredibly Close", director: "Stephen Daldry", isWinner: false, releaseYear: 2011 },
    { title: "The Help", director: "Tate Taylor", isWinner: false, releaseYear: 2011 },
    { title: "Hugo", director: "Martin Scorsese", isWinner: false, releaseYear: 2011 },
    { title: "Midnight in Paris", director: "Woody Allen", isWinner: false, releaseYear: 2011 },
    { title: "Moneyball", director: "Bennett Miller", isWinner: false, releaseYear: 2011 },
    { title: "The Tree of Life", director: "Terrence Malick", isWinner: false, releaseYear: 2011 },
    { title: "War Horse", director: "Steven Spielberg", isWinner: false, releaseYear: 2011 },
  ],
  2013: [
    { title: "Argo", director: "Ben Affleck", isWinner: true, releaseYear: 2012 },
    { title: "Amour", director: "Michael Haneke", isWinner: false, releaseYear: 2012 },
    { title: "Beasts of the Southern Wild", director: "Benh Zeitlin", isWinner: false, releaseYear: 2012 },
    { title: "Django Unchained", director: "Quentin Tarantino", isWinner: false, releaseYear: 2012 },
    { title: "Les Misérables", director: "Tom Hooper", isWinner: false, releaseYear: 2012 },
    { title: "Life of Pi", director: "Ang Lee", isWinner: false, releaseYear: 2012 },
    { title: "Lincoln", director: "Steven Spielberg", isWinner: false, releaseYear: 2012 },
    { title: "Silver Linings Playbook", director: "David O. Russell", isWinner: false, releaseYear: 2012 },
    { title: "Zero Dark Thirty", director: "Kathryn Bigelow", isWinner: false, releaseYear: 2012 },
  ],
  2014: [
    { title: "12 Years a Slave", director: "Steve McQueen", isWinner: true, releaseYear: 2013 },
    { title: "American Hustle", director: "David O. Russell", isWinner: false, releaseYear: 2013 },
    { title: "Captain Phillips", director: "Paul Greengrass", isWinner: false, releaseYear: 2013 },
    { title: "Dallas Buyers Club", director: "Jean-Marc Vallée", isWinner: false, releaseYear: 2013 },
    { title: "Gravity", director: "Alfonso Cuarón", isWinner: false, releaseYear: 2013 },
    { title: "Her", director: "Spike Jonze", isWinner: false, releaseYear: 2013 },
    { title: "Nebraska", director: "Alexander Payne", isWinner: false, releaseYear: 2013 },
    { title: "Philomena", director: "Stephen Frears", isWinner: false, releaseYear: 2013 },
    { title: "The Wolf of Wall Street", director: "Martin Scorsese", isWinner: false, releaseYear: 2013 },
  ],
  2015: [
    { title: "Birdman or (The Unexpected Virtue of Ignorance)", director: "Alejandro González Iñárritu", isWinner: true, releaseYear: 2014 },
    { title: "American Sniper", director: "Clint Eastwood", isWinner: false, releaseYear: 2014 },
    { title: "Boyhood", director: "Richard Linklater", isWinner: false, releaseYear: 2014 },
    { title: "The Grand Budapest Hotel", director: "Wes Anderson", isWinner: false, releaseYear: 2014 },
    { title: "The Imitation Game", director: "Morten Tyldum", isWinner: false, releaseYear: 2014 },
    { title: "Selma", director: "Ava DuVernay", isWinner: false, releaseYear: 2014 },
    { title: "The Theory of Everything", director: "James Marsh", isWinner: false, releaseYear: 2014 },
    { title: "Whiplash", director: "Damien Chazelle", isWinner: false, releaseYear: 2014 },
  ],
  2016: [
    { title: "Spotlight", director: "Tom McCarthy", isWinner: true, releaseYear: 2015 },
    { title: "The Big Short", director: "Adam McKay", isWinner: false, releaseYear: 2015 },
    { title: "Bridge of Spies", director: "Steven Spielberg", isWinner: false, releaseYear: 2015 },
    { title: "Brooklyn", director: "John Crowley", isWinner: false, releaseYear: 2015 },
    { title: "Mad Max: Fury Road", director: "George Miller", isWinner: false, releaseYear: 2015 },
    { title: "The Martian", director: "Ridley Scott", isWinner: false, releaseYear: 2015 },
    { title: "The Revenant", director: "Alejandro González Iñárritu", isWinner: false, releaseYear: 2015 },
    { title: "Room", director: "Lenny Abrahamson", isWinner: false, releaseYear: 2015 },
  ],
  2017: [
    { title: "Moonlight", director: "Barry Jenkins", isWinner: true, releaseYear: 2016 },
    { title: "Arrival", director: "Denis Villeneuve", isWinner: false, releaseYear: 2016 },
    { title: "Fences", director: "Denzel Washington", isWinner: false, releaseYear: 2016 },
    { title: "Hacksaw Ridge", director: "Mel Gibson", isWinner: false, releaseYear: 2016 },
    { title: "Hell or High Water", director: "David Mackenzie", isWinner: false, releaseYear: 2016 },
    { title: "Hidden Figures", director: "Theodore Melfi", isWinner: false, releaseYear: 2016 },
    { title: "La La Land", director: "Damien Chazelle", isWinner: false, releaseYear: 2016 },
    { title: "Lion", director: "Garth Davis", isWinner: false, releaseYear: 2016 },
    { title: "Manchester by the Sea", director: "Kenneth Lonergan", isWinner: false, releaseYear: 2016 },
  ],
  2018: [
    { title: "The Shape of Water", director: "Guillermo del Toro", isWinner: true, releaseYear: 2017 },
    { title: "Call Me by Your Name", director: "Luca Guadagnino", isWinner: false, releaseYear: 2017 },
    { title: "Darkest Hour", director: "Joe Wright", isWinner: false, releaseYear: 2017 },
    { title: "Dunkirk", director: "Christopher Nolan", isWinner: false, releaseYear: 2017 },
    { title: "Get Out", director: "Jordan Peele", isWinner: false, releaseYear: 2017 },
    { title: "Lady Bird", director: "Greta Gerwig", isWinner: false, releaseYear: 2017 },
    { title: "Phantom Thread", director: "Paul Thomas Anderson", isWinner: false, releaseYear: 2017 },
    { title: "The Post", director: "Steven Spielberg", isWinner: false, releaseYear: 2017 },
    { title: "Three Billboards Outside Ebbing, Missouri", director: "Martin McDonagh", isWinner: false, releaseYear: 2017 },
  ],
  2019: [
    { title: "Green Book", director: "Peter Farrelly", isWinner: true, releaseYear: 2018 },
    { title: "BlacKkKlansman", director: "Spike Lee", isWinner: false, releaseYear: 2018 },
    { title: "Black Panther", director: "Ryan Coogler", isWinner: false, releaseYear: 2018 },
    { title: "Bohemian Rhapsody", director: "Bryan Singer", isWinner: false, releaseYear: 2018 },
    { title: "The Favourite", director: "Yorgos Lanthimos", isWinner: false, releaseYear: 2018 },
    { title: "Roma", director: "Alfonso Cuarón", isWinner: false, releaseYear: 2018 },
    { title: "A Star Is Born", director: "Bradley Cooper", isWinner: false, releaseYear: 2018 },
    { title: "Vice", director: "Adam McKay", isWinner: false, releaseYear: 2018 },
  ],
  2020: [
    { title: "Parasite", director: "Bong Joon-ho", isWinner: true, releaseYear: 2019 },
    { title: "Ford v Ferrari", director: "James Mangold", isWinner: false, releaseYear: 2019 },
    { title: "The Irishman", director: "Martin Scorsese", isWinner: false, releaseYear: 2019 },
    { title: "Jojo Rabbit", director: "Taika Waititi", isWinner: false, releaseYear: 2019 },
    { title: "Joker", director: "Todd Phillips", isWinner: false, releaseYear: 2019 },
    { title: "Little Women", director: "Greta Gerwig", isWinner: false, releaseYear: 2019 },
    { title: "Marriage Story", director: "Noah Baumbach", isWinner: false, releaseYear: 2019 },
    { title: "1917", director: "Sam Mendes", isWinner: false, releaseYear: 2019 },
    { title: "Once Upon a Time in Hollywood", director: "Quentin Tarantino", isWinner: false, releaseYear: 2019 },
  ],
  2021: [
    { title: "Nomadland", director: "Chloé Zhao", isWinner: true, releaseYear: 2020 },
    { title: "The Father", director: "Florian Zeller", isWinner: false, releaseYear: 2020 },
    { title: "Judas and the Black Messiah", director: "Shaka King", isWinner: false, releaseYear: 2021 },
    { title: "Mank", director: "David Fincher", isWinner: false, releaseYear: 2020 },
    { title: "Minari", director: "Lee Isaac Chung", isWinner: false, releaseYear: 2020 },
    { title: "Promising Young Woman", director: "Emerald Fennell", isWinner: false, releaseYear: 2020 },
    { title: "Sound of Metal", director: "Darius Marder", isWinner: false, releaseYear: 2019 },
    { title: "The Trial of the Chicago 7", director: "Aaron Sorkin", isWinner: false, releaseYear: 2020 },
  ],
  2022: [
    { title: "CODA", director: "Sian Heder", isWinner: true, releaseYear: 2021 },
    { title: "Belfast", director: "Kenneth Branagh", isWinner: false, releaseYear: 2021 },
    { title: "Don't Look Up", director: "Adam McKay", isWinner: false, releaseYear: 2021 },
    { title: "Drive My Car", director: "Ryusuke Hamaguchi", isWinner: false, releaseYear: 2021 },
    { title: "Dune", director: "Denis Villeneuve", isWinner: false, releaseYear: 2021 },
    { title: "King Richard", director: "Reinaldo Marcus Green", isWinner: false, releaseYear: 2021 },
    { title: "Licorice Pizza", director: "Paul Thomas Anderson", isWinner: false, releaseYear: 2021 },
    { title: "Nightmare Alley", director: "Guillermo del Toro", isWinner: false, releaseYear: 2021 },
    { title: "The Power of the Dog", director: "Jane Campion", isWinner: false, releaseYear: 2021 },
    { title: "tick, tick... BOOM!", director: "Lin-Manuel Miranda", isWinner: false, releaseYear: 2021 },
  ],
  2023: [
    { title: "Everything Everywhere All at Once", director: "Daniel Kwan & Daniel Scheinert", isWinner: true, releaseYear: 2022 },
    { title: "All Quiet on the Western Front", director: "Edward Berger", isWinner: false, releaseYear: 2022 },
    { title: "The Banshees of Inisherin", director: "Martin McDonagh", isWinner: false, releaseYear: 2022 },
    { title: "Elvis", director: "Baz Luhrmann", isWinner: false, releaseYear: 2022 },
    { title: "The Fabelmans", director: "Steven Spielberg", isWinner: false, releaseYear: 2022 },
    { title: "Tár", director: "Todd Field", isWinner: false, releaseYear: 2022 },
    { title: "Top Gun: Maverick", director: "Joseph Kosinski", isWinner: false, releaseYear: 2022 },
    { title: "Triangle of Sadness", director: "Ruben Östlund", isWinner: false, releaseYear: 2022 },
    { title: "Women Talking", director: "Sarah Polley", isWinner: false, releaseYear: 2022 },
    { title: "Avatar: The Way of Water", director: "James Cameron", isWinner: false, releaseYear: 2022 },
  ],
  2024: [
    { title: "Oppenheimer", director: "Christopher Nolan", isWinner: true, releaseYear: 2023 },
    { title: "American Fiction", director: "Cord Jefferson", isWinner: false, releaseYear: 2023 },
    { title: "Anatomy of a Fall", director: "Justine Triet", isWinner: false, releaseYear: 2023 },
    { title: "Barbie", director: "Greta Gerwig", isWinner: false, releaseYear: 2023 },
    { title: "The Holdovers", director: "Alexander Payne", isWinner: false, releaseYear: 2023 },
    { title: "Killers of the Flower Moon", director: "Martin Scorsese", isWinner: false, releaseYear: 2023 },
    { title: "Maestro", director: "Bradley Cooper", isWinner: false, releaseYear: 2023 },
    { title: "Past Lives", director: "Celine Song", isWinner: false, releaseYear: 2023 },
    { title: "Poor Things", director: "Yorgos Lanthimos", isWinner: false, releaseYear: 2023 },
    { title: "The Zone of Interest", director: "Jonathan Glazer", isWinner: false, releaseYear: 2023 },
  ],
  2025: [
    { title: "Anora", director: "Sean Baker", isWinner: true, releaseYear: 2024 },
    { title: "The Brutalist", director: "Brady Corbet", isWinner: false, releaseYear: 2024 },
    { title: "A Complete Unknown", director: "James Mangold", isWinner: false, releaseYear: 2024 },
    { title: "Conclave", director: "Edward Berger", isWinner: false, releaseYear: 2024 },
    { title: "Dune: Part Two", director: "Denis Villeneuve", isWinner: false, releaseYear: 2024 },
    { title: "Emilia Pérez", director: "Jacques Audiard", isWinner: false, releaseYear: 2024 },
    { title: "I'm Still Here", director: "Walter Salles", isWinner: false, releaseYear: 2024 },
    { title: "Nickel Boys", director: "RaMell Ross", isWinner: false, releaseYear: 2024 },
    { title: "The Substance", director: "Coralie Fargeat", isWinner: false, releaseYear: 2024 },
    { title: "Wicked", director: "Jon M. Chu", isWinner: false, releaseYear: 2024 },
  ],
  2026: [
    { title: "One Battle After Another", director: "Paul Thomas Anderson", isWinner: true, releaseYear: 2025 },
    { title: "Bugonia", director: "Yorgos Lanthimos", isWinner: false, releaseYear: 2025 },
    { title: "F1", director: "Joseph Kosinski", isWinner: false, releaseYear: 2025 },
    { title: "Frankenstein", director: "Guillermo del Toro", isWinner: false, releaseYear: 2025 },
    { title: "Hamnet", director: "Chloé Zhao", isWinner: false, releaseYear: 2025 },
    { title: "Marty Supreme", director: "Josh Safdie", isWinner: false, releaseYear: 2025 },
    { title: "The Secret Agent", director: "Kleber Mendonça Filho", isWinner: false, releaseYear: 2025 },
    { title: "Sentimental Value", director: "Joachim Trier", isWinner: false, releaseYear: 2025 },
    { title: "Sinners", director: "Ryan Coogler", isWinner: false, releaseYear: 2025 },
    { title: "Train Dreams", director: "Clint Bentley", isWinner: false, releaseYear: 2025 },
  ],
}

export const CEREMONY_YEARS = Object.keys(oscarData).map(Number).sort()

export const TOTAL_FILMS = Object.values(oscarData).reduce(
  (sum, nominees) => sum + nominees.length,
  0
)
